[[headers]]
  for = "/*"
  [headers.values]
    # 1. ANTI-CLICKJACKING: Evita que un atacante meta tu app dentro de un iframe en otra web.
    X-Frame-Options = "DENY"

    # 2. ANTI-XSS: Fuerza al navegador a bloquear la página si detecta una inyección de código.
    X-XSS-Protection = "1; mode=block"

    # 3. ANTI-MIME-SNIFFING: Evita que el navegador intente adivinar el tipo de archivo.
    X-Content-Type-Options = "nosniff"

    # 4. PRIVACIDAD DE REFERENCIA: Protege el origen de tus peticiones.
    Referrer-Policy = "strict-origin-when-cross-origin"

    # 5. CONTROL DE HARDWARE EXCLUSIVO: Autoriza el uso del micrófono únicamente a tu dominio.
    Permissions-Policy = "microphone=(self)"

    # 6. POLÍTICA DE SEGURIDAD DE CONTENIDO (CSP): El escudo definitivo.
    # ¡ACTUALIZADO! Se agregó https://api.ipify.org en connect-src para permitir la telemetría de IPs en el Login Híbrido.
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; media-src 'self' blob:; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://api.ipify.org;"

# Opcional pero recomendado para Vue Router (evita errores 404 al recargar la página en producción)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200